# Generated by Django 5.2 on 2025-05-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(max_length=20),
        ),
    ]
